[versions]
androidx-activity = "1.7.2"
androidx-compose-animation = "1.5.0"
androidx-compose-foundation = "1.5.0"
androidx-compose-material = "1.4.3"
androidx-compose-runtime = "1.5.0"
androidx-compose-ui = "1.5.0"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.6.0"
com-google-accompanist = "0.31.6-rc"
com-squareup-okhttp3 = "4.11.0"
com-squareup-retrofit2 = "2.9.0"
io-coil-kt = "2.4.0"
org-jetbrains-kotlin = "1.8.21"
org-jetbrains-kotlinx = "1.7.3"
billing-ktx = "6.0.1"

[libraries]
androidx-datastore = "androidx.datastore:datastore-preferences:1.0.0"
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-browser = "androidx.browser:browser:1.6.0"
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-compose-animation" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-foundation-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx-compose-foundation" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-material" }
androidx-compose-material-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }
androidx-compose-material3 = "androidx.compose.material3:material3:1.1.1"
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-core-core-ktx = "androidx.core:core-ktx:1.10.1"
androidx-core-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-preference = "androidx.preference:preference-ktx:1.2.1"
com-android-tools-build-gradle = "com.android.tools.build:gradle:8.1.0"
com-google-accompanist-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "com-google-accompanist" }
com-google-android-gms-play-services-base = "com.google.android.gms:play-services-base:18.2.0"
com-google-code-gson = "com.google.code.gson:gson:2.10.1"
com-google-firebase-firebase-analytics-ktx = "com.google.firebase:firebase-analytics-ktx:21.3.0"
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2" }
io-coil-kt-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "io-coil-kt" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
com-android-billingclient-billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-ktx" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version = "2.9.8" }

[bundles]
core-androidx = [
    "androidx-core-core-ktx",
    "androidx-lifecycle-lifecycle-livedata-core-ktx",
    "androidx-lifecycle-lifecycle-viewmodel-ktx",
]
core-firebase = [
    "com-google-firebase-firebase-analytics-ktx",
]
core-jetbrains = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]
core-squareup = [
    "com-squareup-okhttp3-logging-interceptor",
    "com-squareup-retrofit2-converter-gson",
    "com-squareup-retrofit2-retrofit",
]
ktx-androidx = [
    "androidx-browser",
    "androidx-navigation-navigation-compose",
]
# FOR JCHUCOMPONENTS KTX
ktx-google = [
    "com-google-android-gms-play-services-base",
    "com-google-code-gson",
]
ktx-third-party = [
    "io-coil-kt-coil-compose",
]
# FOR JCHUCOMPONENTS QR
qr-androidx = [
    "androidx-core-core-ktx",
]
qr-third-party = [
    "com-squareup-okhttp3-okhttp",
]
# FOR JCHUCOMPONENTS UI
ui-accompanist = [
    "com-google-accompanist-accompanist-systemuicontroller",
]
ui-androidx = [
    "androidx-core-core-splashscreen",
]
ui-compose = [
    "androidx-activity-activity-compose",
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-foundation-foundation-layout",
    "androidx-compose-material",
    "androidx-compose-material-material-icons-extended",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-ui-tooling",
    "androidx-navigation-navigation-compose",
    "io-coil-kt-coil-compose",
]
# FOR JCHUCOMPONENTS PAY
pay-android = [
    "com-android-billingclient-billing-ktx"
]
pay-jetbrains = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]

# FOR JCHUCOMPONENTS PREFERENCES
preferences-androidx = [
    "androidx-datastore",
    "androidx-preference",
    "androidx-lifecycle-lifecycle-runtime-compose",
]
preferences-google = [
    "com-google-code-gson",
]
preferences-compose = [
    "androidx-compose-runtime",
    "androidx-compose-ui",
]